### PR TITLE
Check permissions and status for upload document stores

### LINKED ISSUE #7: Block upload page if no upload folder is activated
## Steps to reproduce
- navigate to `civicrm/admin/civioffice/settings`
- disable public and / or private uplodas
- navigate to: `civicrm/civioffice/document_upload`
- upload a file

## Current
- Upload works

## Expected
- Upload or page should somehow be blocked due to permissions

### PR DESCRIPTION
**Pull request by jensschuppe**
Fixes #7.

This replaces the simple access check of the upload store's upload form with an access callback checking for whether at least one upload mode (private files, shared files) is enabled, and for each mode's upload form whether the requested mode is enabled. The upload page's tabs are also only included when the particular upload mode is enabled.

This does not hide the *Upload documents* menu item, because navigation menu items can only be filtered by permissions and do not take access restrictions for the route itself into account. The menu item can also not be defined conditionally because the menu is cached. So with no upload store enabled, following the menu link results in an *Access denied* response.

*systopia-reference: 27681*

### CODE REVIEW

File: CRM/Civioffice/DocumentStore/Upload.php [hunk 1]
```diff
@@ -217,4 +217,20 @@ public function getDescription(): string
...
-}
\ No newline at end of file
+
+  public static function access(): bool {
+    $common = CRM_Utils_Request::retrieve('common', 'Boolean');
+    // Check permission.
+    return CRM_Core_Permission::check('access CiviOffice')
+      && (
+        // Check for current mode (current tab).
+        isset($common) && (new self($common))->isReady()
```
Comment (dontub) [inline CRM/Civioffice/DocumentStore/Upload.php:227]: `isset($common)` could be `$common === NULL` (same below)

File: CRM/Civioffice/Form/DocumentUpload/TabHeader.php [hunk 2]
```diff
@@ -54,7 +54,7 @@ public static function build(&$form) {
   /**
    * @param CRM_Civioffice_Form_DocumentUpload $form
    *
-   * @return array
+   * @return array<string, array<string, mixed>>
    * @throws Exception
    */
   public static function process(&$form) {
```
Comment (dontub) [inline CRM/Civioffice/Form/DocumentUpload/TabHeader.php:60]: You might also want to add the PHP return type hint `: array`.

File: CRM/Civioffice/DocumentStore/Upload.php [hunk 3]
```diff
@@ -217,4 +217,20 @@ public function getDescription(): string
...
+        // Check without mode (the tab set).
+        || !isset($common) && (
+          (new self(FALSE))->isReady()
+          || (new self(TRUE))->isReady()
```
Comment (dontub) [inline CRM/Civioffice/DocumentStore/Upload.php:231]: I'd suggest to write lines 230 and 231 in one line:
```php
(new self(FALSE))->isReady() || (new self(TRUE))->isReady()
```

Or including line 229:
```php
|| $common === NULL && (new self(FALSE))->isReady() || (new self(TRUE))->isReady())
```

**Review by dontub — CHANGES_REQUESTED** [review]

**Review by dontub — APPROVED** [review]
