### PR TITLE
Avoid fatal error if unoconv lock file cannot be opened

### LINKED ISSUE #95: Invalid lock file path makes configuration page inaccessible
Follow-up to #49.

When the lock file can not be created in the given destination (e. g. after a migration of the website with the configured path not being writable anymore), the CiviOffice configuration page crashes completely and requires you to manually change lock file paths in each renderer configuration in the database, because without the configuration interface the offending configuration can't be changed.

```
TypeError: flock(): Argument #1 ($stream) must be of type resource, bool given in flock() (line 588 of /path/to/de.systopia.civioffice/CRM/Civioffice/DocumentRendererType/LocalUnoconv.php).
```

There should be an error message only, giving the user the chance to correct the configuration via the UI.

This should be part of `1.0.0`.

### PR DESCRIPTION
**Pull request by dontub**
Fixes #95.

The result of `fopen()` is now checked before giving it as argument to `flock()`. Previously it resulted in a fatal PHP error when `fopen()` returned `false`.

`\CRM_Core_Session::setStatus()` is used to display errors.

Because two new translatable strings where added I've extracted all translatable strings and made a German translation where it was missing. (I think at many places the German translation as well as the English original is far from being perfect...)

systopia-reference: 27681

### CODE REVIEW

File: CRM/Civioffice/DocumentRendererType/LocalUnoconv.php [hunk 1]
```diff
@@ -121,7 +121,8 @@ public function isReady(): bool
                 return false;
             }
         } catch (Exception $ex) {
-            Civi::log()->debug("CiviOffice: Unoconv generic exception in isReady() check");
+            CRM_Core_Session::setStatus($ex->getMessage(), E::ts('CiviOffice Error'), 'error');
```
Comment (jensschuppe) [inline CRM/Civioffice/DocumentRendererType/LocalUnoconv.php:124]: Not sure we want to expose the actual exception message to the UI. Maybe something like *Unknown error, see the error log for details.* …?

File: CRM/Civioffice/DocumentRendererType/LocalUnoconv.php [hunk 2]
```diff
@@ -581,13 +582,16 @@ protected function runCommand($command)
     /**
      * wait for the unoconv resource to become available
      */
-    protected function lock()
+    protected function lock(): void
     {
-        $lock_file_path = $this->unoconv_lock_file_path;
-        if ($lock_file_path) {
-            $this->unoconv_lock_file = fopen($lock_file_path, "w+");
+        if ($this->unoconv_lock_file_path) {
```
Comment (jensschuppe) [inline CRM/Civioffice/DocumentRendererType/LocalUnoconv.php:587]: The property is not a bool and should either be a string or not set, let's use `isset()` here?

File: CRM/Civioffice/DocumentRendererType/LocalUnoconv.php [hunk 3]
```diff
@@ -581,13 +582,16 @@ protected function runCommand($command)
...
+            $this->unoconv_lock_file = fopen($this->unoconv_lock_file_path, 'w+');
+            if ($this->unoconv_lock_file === FALSE) {
```
Comment (jensschuppe) [inline CRM/Civioffice/DocumentRendererType/LocalUnoconv.php:589]: Use *Yoda condition* style?

File: l10n/de_DE/LC_MESSAGES/civioffice.po [hunk 4]
```diff
@@ -411,6 +420,139 @@ msgstr "Hochladen privater Dokumente aktiviert"
...
+msgid "Live Snippets"
+msgstr "Live-Snippets"
+
+#: ang/civiofficeSearchTasks/civiofficeSearchTaskRender.html
+msgid ""
+"The result will be opened in a new browser tab. Your browser may ask to open "
+"a popup."
+msgstr ""
+"Das Ergebnis wird in einem neuen Browser-Tab geöffnet. Ihr fragt Sie "
+"möglicherweise, ein Popup zu öffnen."
```
Comment (jensschuppe) [inline l10n/de_DE/LC_MESSAGES/civioffice.po:546]: Rewording suggestion: *Ihr Browser fordert Sie ggf. auf, das Öffnen eines Popup-Fensters zu erlauben.*, at least a missing *Browser*

File: l10n/de_DE/LC_MESSAGES/civioffice.po [hunk 5]
```diff
@@ -456,10 +598,281 @@ msgstr ""
...
+"Such a file is created automatically at the location shown below. Please "
+"note: This path needs to be equal in every civicrm environment on this "
+"server. Otherwise, locking is only active for this very civicrm instance!"
+msgstr ""
+"Wir empfehlen eindringlich eine System-weite Sperrdatei zu erstellen, um den "
+"Zugriff zu synchronisieren. (Es kann nur jeweils ein unoconv Prozess zur "
+"gleichen Zeit laufen.) Die Datei wird automatisch am unten angezeigten Ort "
+"erstellt. Bitte beachten: Der Pfad muss auf allen CiviCRM-Umgebungen auf "
+"diesem Server gleich sein. Anderenfalls ist das Sperren nur für diese "
+"CiviCRM-Instanz aktiv."
```
Comment (jensschuppe) [inline l10n/de_DE/LC_MESSAGES/civioffice.po:655]: Rewording suggestion: *Es wird ausdrücklich empfohlen …*

File: l10n/de_DE/LC_MESSAGES/civioffice.po [hunk 6]
```diff
@@ -456,10 +598,281 @@ msgstr ""
...
+
+#: templates/CRM/Civioffice/Form/DocumentRenderer/Settings/LocalUnoconv.tpl
+msgid ""
+"Run the DOCX document through the converter prior to processing in order to "
+"optimise/repair possibly corrupted CiviCRM tokens in the document."
+msgstr ""
+"DOCX-Dokumente vor der Verarbeitung durch den Konverter laufen lassen, um "
+"sie zu optimieren und mögliche korrupte CiviCRM-Tokens zu reparieren."
```
Comment (jensschuppe) [inline l10n/de_DE/LC_MESSAGES/civioffice.po:663]: Let's replace *korrupte* with *beschädigte*.

Comment (jensschuppe) [inline l10n/de_DE/LC_MESSAGES/civioffice.po:663]: Arguing for the plural of *Token* being *Token* in German, not *Tokens*, or let's just use *CiviCRM-Platzhalter*.

File: l10n/de_DE/LC_MESSAGES/civioffice.po [hunk 7]
```diff
@@ -456,10 +598,281 @@ msgstr ""
...
+
+#: templates/CRM/Civioffice/Form/DocumentRenderer/Settings/LocalUnoconv.tpl
+msgid ""
+"Whether to replace tokens using a PHPWord template processor, so that HTML "
+"in Live Snippets can be converted to OOXML."
+msgstr ""
+"Ob Tokens mit dem PHPWord-Vorlagen-Prozessor ersetzt werden, sodass HTML in "
+"Live-Snippets zu OOXML konvertiert werden kann."
```
Comment (jensschuppe) [inline l10n/de_DE/LC_MESSAGES/civioffice.po:671]: *Token* or *Platzhalter*

File: l10n/de_DE/LC_MESSAGES/civioffice.po [hunk 8]
```diff
@@ -456,10 +598,281 @@ msgstr ""
...
+"Please click the download button only once. Clicking the button will trigger "
+"generating your zip file which may take a long time depending on the size "
+"and complexity of your documents.<br>Afterwards please always use the \"back "
+"to previous page\" button to finish this process"
+msgstr ""
+"Bitte klicken Sie den Knopf zum Herunterladen nur einmal. Das Klicken des "
+"Knopfes stößt das Erstellen einer ZIP-Datei an, was einige Zeit benötigen "
+"kann, abhängig von der Größe und der Komplexität Ihrer Dokumente. Klicken "
+"Sie danach immer den Knopf \"Zurück zu vorheriger Seite\", um den Prozess "
+"abzuschließen"
```
Comment (jensschuppe) [inline l10n/de_DE/LC_MESSAGES/civioffice.po:721]: Suggesting to replace *Klicken* with *Betätigen* (you know, touch devices can't "click"), although the source string doesn't provide a good wording in the first place.

File: l10n/de_DE/LC_MESSAGES/civioffice.po [hunk 9]
```diff
@@ -456,10 +598,281 @@ msgstr ""
...
+"This page lists all tokens CiviOffice is potentially able to replace in "
+"documents, however, this depends on the context. E.g. contribution tokens "
+"are only available in a context of generating documents for particular "
+"contributions, whereas general tokens, such as for domain or date, are "
+"always available."
+msgstr ""
+"Diese Seite listet alle CiviOffice-Tokens auf, die in Dokumenten verwendet "
+"werden können. Die Verfügbarkeit hängt vom Kontext ab. Bspw. sind Zuwendungs-"
+"Tokens nur verfügbar, wenn Dokumente für Zuwendungen generiert werden. "
+"Allgemeine Tokens, wie die Domäne oder das Datum, sind immer verfügbar."
```
Comment (jensschuppe) [inline l10n/de_DE/LC_MESSAGES/civioffice.po:878]: *Token* or *Platzhalter* instead of *Tokens*

**Review by jensschuppe — CHANGES_REQUESTED** [review]
Let's not dwell too much on the suggestions regarding translations.

File: CRM/Civioffice/DocumentRendererType/LocalUnoconv.php (hunk 1 above)
Comment (jensschuppe) [reply CRM/Civioffice/DocumentRendererType/LocalUnoconv.php:124]: I'm not married to my suggestion, but displaying raw exception messages in the UI doesn't feel right …

File: l10n/de_DE/LC_MESSAGES/civioffice.po (hunk 6 above)
Comment (dontub) [reply l10n/de_DE/LC_MESSAGES/civioffice.po:663]: Yes, there should be no *s* at the end. As *Token* is also used in the CiviCRM translation I think we should keep that word, even though I'd prefer *Platzhalter*.

File: CRM/Civioffice/DocumentRendererType/LocalUnoconv.php (hunk 2 above)
Comment (dontub) [reply CRM/Civioffice/DocumentRendererType/LocalUnoconv.php:587]: I added the PHP type hint `?string` to the property and changed the condition to `NULL !== $this->unoconv_lock_file_path && '' !== $this->unoconv_lock_file_path`.

**Review by jensschuppe — APPROVED** [review]
