### PR TITLE
`trim()` paths in local store configuration

### LINKED ISSUE #77: directory paths with leading whitespace lead to uploaded template files not being displayed when creating a new document
**Observation**

If a path that has been set as `Local Folder` in `civioffice` settings is prefixed with one or more whitespaces, then none of the `Documents` that have been stored under that path can be selected when creating a new `CiviOffice Document`.

**Steps to reproduce**

configure civioffice first

- open `civioffice` settings at `civicrm/admin/civioffice/settings`
- open `configure` `Local Folder` in `CiviOffice Document Stores`
- place one more whitespace in front of the given path
  - `  /path/to/your/folder` instead of `/path/to/your/folder`
- save settings

then (if not done already)

- upload a template file to the specified path on server

then try to create a document based on a available template file 

- open a contact
- click on `Action`
- click on `Create CiviOffice Document` (or the activity name you configured)
- in the new dialog window open the `Document` drop down menu in order to show available templates stored in your `Local Folder`
- no document are shown in the drop down menu

**Version**

observed with version `1.0-beta8`

### PR DESCRIPTION
**Pull request by jensschuppe**
Fixes #77.

This `trim()`s paths in the local document store's configuration before saving them, and once again when using them (for paths with whitespace already present in the config). Existing (default) values in the config form are not being trimmed.

*systopia-reference: 27681*

### CODE REVIEW

File: CRM/Civioffice/DocumentStore/Local.php [hunk 1]
```diff
@@ -23,10 +23,10 @@ class CRM_Civioffice_DocumentStore_Local extends CRM_Civioffice_DocumentStore
     const LOCAL_STATIC_PATH_SETTINGS_KEY = 'civioffice_store_local_static_path';
     const LOCAL_TEMP_PATH_SETTINGS_KEY = 'civioffice_store_local_temp_path';
 
-    /** @var string local folder this store has access to */
+    /** @var string|null local folder this store has access to */
     protected $base_folder;
```
Comment (dontub) [inline CRM/Civioffice/DocumentStore/Local.php:27]: PHP type hint `?string` might be added.

File: CRM/Civioffice/DocumentStore/Local.php [hunk 2]
```diff
@@ -23,10 +23,10 @@ class CRM_Civioffice_DocumentStore_Local extends CRM_Civioffice_DocumentStore
...
 
-    /** @var string local folder this store has access to */
+    /** @var string|null local folder this store has access to */
     protected $temp_folder;
```
Comment (dontub) [inline CRM/Civioffice/DocumentStore/Local.php:30]: PHP type hint `?string` might be added.

File: CRM/Civioffice/DocumentStore/Local.php [hunk 3]
```diff
@@ -35,15 +35,24 @@ class CRM_Civioffice_DocumentStore_Local extends CRM_Civioffice_DocumentStore
...
+  /**
+   * @phpstan-param string $uri
+   * @phpstan-param string $name
+   */
+  public function __construct($uri, $name, bool $readonly, bool $has_subfolders) {
+    parent::__construct($uri, $name);
+
+    /** @phpstan-var string|null $baseFolder */
+    $baseFolder = Civi::settings()->get(self::LOCAL_STATIC_PATH_SETTINGS_KEY);
+    $this->base_folder = is_string($baseFolder) ? trim($baseFolder) : $baseFolder;
```
Comment (dontub) [inline CRM/Civioffice/DocumentStore/Local.php:47]: Shouldn't it be
`$this->base_folder = is_string($baseFolder) ? trim($baseFolder) : NULL;`?

File: CRM/Civioffice/DocumentStore/Local.php [hunk 4]
```diff
@@ -35,15 +35,24 @@ class CRM_Civioffice_DocumentStore_Local extends CRM_Civioffice_DocumentStore
...
+
+    /** @phpstan-var string|null $tempFolder */
+    $tempFolder = Civi::settings()->get(self::LOCAL_TEMP_PATH_SETTINGS_KEY);
+    $this->temp_folder = is_string($tempFolder) ? trim($tempFolder) : $tempFolder;
```
Comment (dontub) [inline CRM/Civioffice/DocumentStore/Local.php:51]: Shouldn't it be `$this->temp_folder = is_string($tempFolder) ? trim($tempFolder) : NULL;`?

File: CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php [hunk 5]
```diff
@@ -63,47 +63,60 @@ public function buildQuickForm()
...
-            $local_temp_folder = $this->_submitValues['local_temp_folder'];
-            if (!file_exists($local_temp_folder) && !mkdir($local_temp_folder, 0777, true)) {
-              $this->_errors['local_temp_folder'] = E::ts('Could not create directory');
-            } else if (!is_dir($local_temp_folder)) {
-                $this->_errors['local_temp_folder'] = E::ts("This is not a folder");
-            } else if (!is_readable($local_temp_folder)) {
-                $this->_errors['local_temp_folder'] = E::ts("This folder cannot be accessed");
-            }
+        else {
+          if (!is_readable($local_folder)) {
```
Comment (dontub) [inline CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php:85]: The `if` could be combined with the `else` above to `elseif` to have one block less.

File: CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php [hunk 6]
```diff
@@ -63,47 +63,60 @@ public function buildQuickForm()
...
+      $local_temp_folder = trim($this->_submitValues['local_temp_folder']);
+      if (!file_exists($local_temp_folder) && !mkdir($local_temp_folder, 0777, TRUE)) {
+        $this->_errors['local_temp_folder'] = E::ts('Could not create directory');
+      }
+      else {
+        if (!is_dir($local_temp_folder)) {
+          $this->_errors['local_temp_folder'] = E::ts('This is not a folder');
+        }
+        else {
+          if (!is_readable($local_temp_folder)) {
```
Comment (dontub) [inline CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php:102]: The `if` could be combined with the `else` above to `elseif` to have one block less.

File: CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php [hunk 7]
```diff
@@ -63,47 +63,60 @@ public function buildQuickForm()
...
-    {
-        $values = $this->exportValues();
+    return (0 == count($this->_errors));
+  }
 
-        // store
-        Civi::settings()->set(CRM_Civioffice_DocumentStore_Local::LOCAL_STATIC_PATH_SETTINGS_KEY, $values['local_folder']);
-        Civi::settings()->set(CRM_Civioffice_DocumentStore_Local::LOCAL_TEMP_PATH_SETTINGS_KEY, $values['local_temp_folder']);
-    }
+  public function postProcess() {
```
Comment (dontub) [inline CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php:112]: Return type hint `: void` could be added.

File: CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php [hunk 8]
```diff
@@ -63,47 +63,60 @@ public function buildQuickForm()
...
+            $this->_errors['local_temp_folder'] = E::ts('This folder cannot be accessed');
+          }
+        }
+      }
     }
 
-    public function postProcess()
-    {
-        $values = $this->exportValues();
+    return (0 == count($this->_errors));
```
Comment (dontub) [inline CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php:109]: Actually the surrounding brackets aren't necessary: `return 0 === count($this->_errors);`

File: CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php [hunk 9]
```diff
@@ -63,47 +63,60 @@ public function buildQuickForm()
...
-            $local_folder = $this->_submitValues['local_folder'];
-            if (!file_exists($local_folder) && !mkdir($local_folder, 0777, true)) {
-              $this->_errors['local_folder'] = E::ts('Could not create directory');
-            } else if (!is_dir($local_folder)) {
-                $this->_errors['local_folder'] = E::ts("This is not a folder");
-            } else if (!is_readable($local_folder)) {
-                $this->_errors['local_folder'] = E::ts("This folder cannot be accessed");
-            }
+    // verify that the folder is 1) there, 2) readable
+    if (!empty($this->_submitValues['local_folder'])) {
```
Comment (dontub) [inline CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php:75]: Should the strings already be trimmed here instead of `postProcess()`?

**Review by dontub — CHANGES_REQUESTED** [review]

File: CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php (hunk 9 above)
Comment (jensschuppe) [reply CRM/Civioffice/Form/LocalDocumentStore/LocalDocumentStoreSettings.php:75]: As in saving the trimmed values in `$this->_submitValues`? Would this have any advantages?

**Review by dontub — CHANGES_REQUESTED** [review]

File: CRM/Civioffice/DocumentStore/Local.php [hunk 10]
```diff
@@ -18,32 +18,50 @@
...
+  /**
+   * @phpstan-param string $uri
+   * @phpstan-param string $name
+   */
+  public function __construct($uri, $name, bool $readonly, bool $has_subfolders) {
+    parent::__construct($uri, $name);
+
+    /** @phpstan-var string|null $baseFolder */
+    $baseFolder = Civi::settings()->get(self::LOCAL_STATIC_PATH_SETTINGS_KEY);
+    $this->base_folder = is_string($baseFolder) ? trim($baseFolder) : NULL;
```
[the remark this answers is not in the document]
Comment (jensschuppe) [reply CRM/Civioffice/DocumentStore/Local.php:57]: I added a `TODO` for that.

**Review by dontub — APPROVED** [review]
